// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: commands_service.proto

package message_contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to initiate a subscription
type ClientToServerStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ClientToServerStream_RequestInitializationCommand
	Command       isClientToServerStream_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToServerStream) Reset() {
	*x = ClientToServerStream{}
	mi := &file_commands_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToServerStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToServerStream) ProtoMessage() {}

func (x *ClientToServerStream) ProtoReflect() protoreflect.Message {
	mi := &file_commands_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToServerStream.ProtoReflect.Descriptor instead.
func (*ClientToServerStream) Descriptor() ([]byte, []int) {
	return file_commands_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClientToServerStream) GetCommand() isClientToServerStream_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ClientToServerStream) GetRequestInitializationCommand() *RequestInitializationCommand {
	if x != nil {
		if x, ok := x.Command.(*ClientToServerStream_RequestInitializationCommand); ok {
			return x.RequestInitializationCommand
		}
	}
	return nil
}

type isClientToServerStream_Command interface {
	isClientToServerStream_Command()
}

type ClientToServerStream_RequestInitializationCommand struct {
	RequestInitializationCommand *RequestInitializationCommand `protobuf:"bytes,1,opt,name=request_initialization_command,json=requestInitializationCommand,proto3,oneof"`
}

func (*ClientToServerStream_RequestInitializationCommand) isClientToServerStream_Command() {}

type RequestInitializationCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInitializationCommand) Reset() {
	*x = RequestInitializationCommand{}
	mi := &file_commands_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInitializationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInitializationCommand) ProtoMessage() {}

func (x *RequestInitializationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_commands_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInitializationCommand.ProtoReflect.Descriptor instead.
func (*RequestInitializationCommand) Descriptor() ([]byte, []int) {
	return file_commands_service_proto_rawDescGZIP(), []int{1}
}

// Response from the server containing a single command to be processed
type ServerToClientStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ServerToClientStream_UpdateDesiredResourcesCommand
	//	*ServerToClientStream_PruneOtherVersionsCommand
	Command       isServerToClientStream_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToClientStream) Reset() {
	*x = ServerToClientStream{}
	mi := &file_commands_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToClientStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClientStream) ProtoMessage() {}

func (x *ServerToClientStream) ProtoReflect() protoreflect.Message {
	mi := &file_commands_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClientStream.ProtoReflect.Descriptor instead.
func (*ServerToClientStream) Descriptor() ([]byte, []int) {
	return file_commands_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServerToClientStream) GetCommand() isServerToClientStream_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ServerToClientStream) GetUpdateDesiredResourcesCommand() *UpdateDesiredResourcesCommand {
	if x != nil {
		if x, ok := x.Command.(*ServerToClientStream_UpdateDesiredResourcesCommand); ok {
			return x.UpdateDesiredResourcesCommand
		}
	}
	return nil
}

func (x *ServerToClientStream) GetPruneOtherVersionsCommand() *PruneOtherVersionsCommand {
	if x != nil {
		if x, ok := x.Command.(*ServerToClientStream_PruneOtherVersionsCommand); ok {
			return x.PruneOtherVersionsCommand
		}
	}
	return nil
}

type isServerToClientStream_Command interface {
	isServerToClientStream_Command()
}

type ServerToClientStream_UpdateDesiredResourcesCommand struct {
	UpdateDesiredResourcesCommand *UpdateDesiredResourcesCommand `protobuf:"bytes,1,opt,name=update_desired_resources_command,json=updateDesiredResourcesCommand,proto3,oneof"`
}

type ServerToClientStream_PruneOtherVersionsCommand struct {
	PruneOtherVersionsCommand *PruneOtherVersionsCommand `protobuf:"bytes,2,opt,name=prune_other_versions_command,json=pruneOtherVersionsCommand,proto3,oneof"`
}

func (*ServerToClientStream_UpdateDesiredResourcesCommand) isServerToClientStream_Command() {}

func (*ServerToClientStream_PruneOtherVersionsCommand) isServerToClientStream_Command() {}

// Add or updates the resources to be monitored
type UpdateDesiredResourcesCommand struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ApplicationInstanceId *ApplicationInstanceId `protobuf:"bytes,1,opt,name=application_instance_id,json=applicationInstanceId,proto3" json:"application_instance_id,omitempty"`
	ClusterId             *ClusterId             `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Version               *Version               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DesiredResources      []*DesiredResource     `protobuf:"bytes,4,rep,name=desired_resources,json=desiredResources,proto3" json:"desired_resources,omitempty"`
	HashSalt              string                 `protobuf:"bytes,5,opt,name=hash_salt,json=hashSalt,proto3" json:"hash_salt,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateDesiredResourcesCommand) Reset() {
	*x = UpdateDesiredResourcesCommand{}
	mi := &file_commands_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDesiredResourcesCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDesiredResourcesCommand) ProtoMessage() {}

func (x *UpdateDesiredResourcesCommand) ProtoReflect() protoreflect.Message {
	mi := &file_commands_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDesiredResourcesCommand.ProtoReflect.Descriptor instead.
func (*UpdateDesiredResourcesCommand) Descriptor() ([]byte, []int) {
	return file_commands_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDesiredResourcesCommand) GetApplicationInstanceId() *ApplicationInstanceId {
	if x != nil {
		return x.ApplicationInstanceId
	}
	return nil
}

func (x *UpdateDesiredResourcesCommand) GetClusterId() *ClusterId {
	if x != nil {
		return x.ClusterId
	}
	return nil
}

func (x *UpdateDesiredResourcesCommand) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *UpdateDesiredResourcesCommand) GetDesiredResources() []*DesiredResource {
	if x != nil {
		return x.DesiredResources
	}
	return nil
}

func (x *UpdateDesiredResourcesCommand) GetHashSalt() string {
	if x != nil {
		return x.HashSalt
	}
	return ""
}

// Removes desired resources that do not match the supplied version for the application instance/cluster
type PruneOtherVersionsCommand struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ApplicationInstanceId *ApplicationInstanceId `protobuf:"bytes,1,opt,name=application_instance_id,json=applicationInstanceId,proto3" json:"application_instance_id,omitempty"`
	ClusterId             *ClusterId             `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Version               *Version               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PruneOtherVersionsCommand) Reset() {
	*x = PruneOtherVersionsCommand{}
	mi := &file_commands_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneOtherVersionsCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneOtherVersionsCommand) ProtoMessage() {}

func (x *PruneOtherVersionsCommand) ProtoReflect() protoreflect.Message {
	mi := &file_commands_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneOtherVersionsCommand.ProtoReflect.Descriptor instead.
func (*PruneOtherVersionsCommand) Descriptor() ([]byte, []int) {
	return file_commands_service_proto_rawDescGZIP(), []int{4}
}

func (x *PruneOtherVersionsCommand) GetApplicationInstanceId() *ApplicationInstanceId {
	if x != nil {
		return x.ApplicationInstanceId
	}
	return nil
}

func (x *PruneOtherVersionsCommand) GetClusterId() *ClusterId {
	if x != nil {
		return x.ClusterId
	}
	return nil
}

func (x *PruneOtherVersionsCommand) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

// A kubernetes resource to be watched by the Kubernetes monitor
type DesiredResource struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	DesiredResourceId *DesiredResourceId      `protobuf:"bytes,1,opt,name=desired_resource_id,json=desiredResourceId,proto3" json:"desired_resource_id,omitempty"`
	ResourceDetails   *DesiredResourceDetails `protobuf:"bytes,2,opt,name=resource_details,json=resourceDetails,proto3" json:"resource_details,omitempty"`
	Manifest          *YamlManifest           `protobuf:"bytes,3,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DesiredResource) Reset() {
	*x = DesiredResource{}
	mi := &file_commands_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredResource) ProtoMessage() {}

func (x *DesiredResource) ProtoReflect() protoreflect.Message {
	mi := &file_commands_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredResource.ProtoReflect.Descriptor instead.
func (*DesiredResource) Descriptor() ([]byte, []int) {
	return file_commands_service_proto_rawDescGZIP(), []int{5}
}

func (x *DesiredResource) GetDesiredResourceId() *DesiredResourceId {
	if x != nil {
		return x.DesiredResourceId
	}
	return nil
}

func (x *DesiredResource) GetResourceDetails() *DesiredResourceDetails {
	if x != nil {
		return x.ResourceDetails
	}
	return nil
}

func (x *DesiredResource) GetManifest() *YamlManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Deployment ID in Octopus
type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_commands_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_commands_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_commands_service_proto_rawDescGZIP(), []int{6}
}

func (x *Version) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_commands_service_proto protoreflect.FileDescriptor

const file_commands_service_proto_rawDesc = "" +
	"\n" +
	"\x16commands_service.proto\x1a\x1dapplication_instance_id.proto\x1a\x10cluster_id.proto\x1a\x19desired_resource_id.proto\x1a\x16resource_details.proto\x1a\x13yaml_manifest.proto\"\x88\x01\n" +
	"\x14ClientToServerStream\x12e\n" +
	"\x1erequest_initialization_command\x18\x01 \x01(\v2\x1d.RequestInitializationCommandH\x00R\x1crequestInitializationCommandB\t\n" +
	"\acommand\"\x1e\n" +
	"\x1cRequestInitializationCommand\"\xeb\x01\n" +
	"\x14ServerToClientStream\x12i\n" +
	" update_desired_resources_command\x18\x01 \x01(\v2\x1e.UpdateDesiredResourcesCommandH\x00R\x1dupdateDesiredResourcesCommand\x12]\n" +
	"\x1cprune_other_versions_command\x18\x02 \x01(\v2\x1a.PruneOtherVersionsCommandH\x00R\x19pruneOtherVersionsCommandB\t\n" +
	"\acommand\"\x9a\x02\n" +
	"\x1dUpdateDesiredResourcesCommand\x12N\n" +
	"\x17application_instance_id\x18\x01 \x01(\v2\x16.ApplicationInstanceIdR\x15applicationInstanceId\x12)\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\v2\n" +
	".ClusterIdR\tclusterId\x12\"\n" +
	"\aversion\x18\x03 \x01(\v2\b.VersionR\aversion\x12=\n" +
	"\x11desired_resources\x18\x04 \x03(\v2\x10.DesiredResourceR\x10desiredResources\x12\x1b\n" +
	"\thash_salt\x18\x05 \x01(\tR\bhashSalt\"\xba\x01\n" +
	"\x19PruneOtherVersionsCommand\x12N\n" +
	"\x17application_instance_id\x18\x01 \x01(\v2\x16.ApplicationInstanceIdR\x15applicationInstanceId\x12)\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\v2\n" +
	".ClusterIdR\tclusterId\x12\"\n" +
	"\aversion\x18\x03 \x01(\v2\b.VersionR\aversion\"\xc4\x01\n" +
	"\x0fDesiredResource\x12B\n" +
	"\x13desired_resource_id\x18\x01 \x01(\v2\x12.DesiredResourceIdR\x11desiredResourceId\x12B\n" +
	"\x10resource_details\x18\x02 \x01(\v2\x17.DesiredResourceDetailsR\x0fresourceDetails\x12)\n" +
	"\bmanifest\x18\x03 \x01(\v2\r.YamlManifestR\bmanifest\"\x1f\n" +
	"\aVersion\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2Z\n" +
	"\x0fCommandsService\x12G\n" +
	"\x13SubscribeToCommands\x12\x15.ClientToServerStream\x1a\x15.ServerToClientStream(\x010\x01B\x96\x01B\x14CommandsServiceProtoP\x01ZNgithub.com/OctopusDeploy/kubernetes-monitor-contracts/go/pkg/message_contracts\xaa\x02+Octopus.Kubernetes.Monitor.MessageContractsb\x06proto3"

var (
	file_commands_service_proto_rawDescOnce sync.Once
	file_commands_service_proto_rawDescData []byte
)

func file_commands_service_proto_rawDescGZIP() []byte {
	file_commands_service_proto_rawDescOnce.Do(func() {
		file_commands_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commands_service_proto_rawDesc), len(file_commands_service_proto_rawDesc)))
	})
	return file_commands_service_proto_rawDescData
}

var file_commands_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_commands_service_proto_goTypes = []any{
	(*ClientToServerStream)(nil),          // 0: ClientToServerStream
	(*RequestInitializationCommand)(nil),  // 1: RequestInitializationCommand
	(*ServerToClientStream)(nil),          // 2: ServerToClientStream
	(*UpdateDesiredResourcesCommand)(nil), // 3: UpdateDesiredResourcesCommand
	(*PruneOtherVersionsCommand)(nil),     // 4: PruneOtherVersionsCommand
	(*DesiredResource)(nil),               // 5: DesiredResource
	(*Version)(nil),                       // 6: Version
	(*ApplicationInstanceId)(nil),         // 7: ApplicationInstanceId
	(*ClusterId)(nil),                     // 8: ClusterId
	(*DesiredResourceId)(nil),             // 9: DesiredResourceId
	(*DesiredResourceDetails)(nil),        // 10: DesiredResourceDetails
	(*YamlManifest)(nil),                  // 11: YamlManifest
}
var file_commands_service_proto_depIdxs = []int32{
	1,  // 0: ClientToServerStream.request_initialization_command:type_name -> RequestInitializationCommand
	3,  // 1: ServerToClientStream.update_desired_resources_command:type_name -> UpdateDesiredResourcesCommand
	4,  // 2: ServerToClientStream.prune_other_versions_command:type_name -> PruneOtherVersionsCommand
	7,  // 3: UpdateDesiredResourcesCommand.application_instance_id:type_name -> ApplicationInstanceId
	8,  // 4: UpdateDesiredResourcesCommand.cluster_id:type_name -> ClusterId
	6,  // 5: UpdateDesiredResourcesCommand.version:type_name -> Version
	5,  // 6: UpdateDesiredResourcesCommand.desired_resources:type_name -> DesiredResource
	7,  // 7: PruneOtherVersionsCommand.application_instance_id:type_name -> ApplicationInstanceId
	8,  // 8: PruneOtherVersionsCommand.cluster_id:type_name -> ClusterId
	6,  // 9: PruneOtherVersionsCommand.version:type_name -> Version
	9,  // 10: DesiredResource.desired_resource_id:type_name -> DesiredResourceId
	10, // 11: DesiredResource.resource_details:type_name -> DesiredResourceDetails
	11, // 12: DesiredResource.manifest:type_name -> YamlManifest
	0,  // 13: CommandsService.SubscribeToCommands:input_type -> ClientToServerStream
	2,  // 14: CommandsService.SubscribeToCommands:output_type -> ServerToClientStream
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_commands_service_proto_init() }
func file_commands_service_proto_init() {
	if File_commands_service_proto != nil {
		return
	}
	file_application_instance_id_proto_init()
	file_cluster_id_proto_init()
	file_desired_resource_id_proto_init()
	file_resource_details_proto_init()
	file_yaml_manifest_proto_init()
	file_commands_service_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientToServerStream_RequestInitializationCommand)(nil),
	}
	file_commands_service_proto_msgTypes[2].OneofWrappers = []any{
		(*ServerToClientStream_UpdateDesiredResourcesCommand)(nil),
		(*ServerToClientStream_PruneOtherVersionsCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commands_service_proto_rawDesc), len(file_commands_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commands_service_proto_goTypes,
		DependencyIndexes: file_commands_service_proto_depIdxs,
		MessageInfos:      file_commands_service_proto_msgTypes,
	}.Build()
	File_commands_service_proto = out.File
	file_commands_service_proto_goTypes = nil
	file_commands_service_proto_depIdxs = nil
}
