// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fetch_container_logs_request.proto

package message_contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchContainerLogsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SessionId             *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Namespace             string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName               string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerName         string                 `protobuf:"bytes,4,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ShowPreviousContainer bool                   `protobuf:"varint,5,opt,name=show_previous_container,json=showPreviousContainer,proto3" json:"show_previous_container,omitempty"`
	ClusterId             *ClusterId             `protobuf:"bytes,6,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FetchContainerLogsRequest) Reset() {
	*x = FetchContainerLogsRequest{}
	mi := &file_fetch_container_logs_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchContainerLogsRequest) ProtoMessage() {}

func (x *FetchContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_container_logs_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*FetchContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_fetch_container_logs_request_proto_rawDescGZIP(), []int{0}
}

func (x *FetchContainerLogsRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *FetchContainerLogsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FetchContainerLogsRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *FetchContainerLogsRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *FetchContainerLogsRequest) GetShowPreviousContainer() bool {
	if x != nil {
		return x.ShowPreviousContainer
	}
	return false
}

func (x *FetchContainerLogsRequest) GetClusterId() *ClusterId {
	if x != nil {
		return x.ClusterId
	}
	return nil
}

var File_fetch_container_logs_request_proto protoreflect.FileDescriptor

const file_fetch_container_logs_request_proto_rawDesc = "" +
	"\n" +
	"\"fetch_container_logs_request.proto\x1a\x10cluster_id.proto\x1a\x10session_id.proto\"\x89\x02\n" +
	"\x19FetchContainerLogsRequest\x12)\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\n" +
	".SessionIdR\tsessionId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x04 \x01(\tR\rcontainerName\x126\n" +
	"\x17show_previous_container\x18\x05 \x01(\bR\x15showPreviousContainer\x12)\n" +
	"\n" +
	"cluster_id\x18\x06 \x01(\v2\n" +
	".ClusterIdR\tclusterIdB\xa0\x01B\x1eFetchContainerLogsRequestProtoP\x01ZNgithub.com/OctopusDeploy/kubernetes-monitor-contracts/go/pkg/message_contracts\xaa\x02+Octopus.Kubernetes.Monitor.MessageContractsb\x06proto3"

var (
	file_fetch_container_logs_request_proto_rawDescOnce sync.Once
	file_fetch_container_logs_request_proto_rawDescData []byte
)

func file_fetch_container_logs_request_proto_rawDescGZIP() []byte {
	file_fetch_container_logs_request_proto_rawDescOnce.Do(func() {
		file_fetch_container_logs_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fetch_container_logs_request_proto_rawDesc), len(file_fetch_container_logs_request_proto_rawDesc)))
	})
	return file_fetch_container_logs_request_proto_rawDescData
}

var file_fetch_container_logs_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fetch_container_logs_request_proto_goTypes = []any{
	(*FetchContainerLogsRequest)(nil), // 0: FetchContainerLogsRequest
	(*SessionId)(nil),                 // 1: SessionId
	(*ClusterId)(nil),                 // 2: ClusterId
}
var file_fetch_container_logs_request_proto_depIdxs = []int32{
	1, // 0: FetchContainerLogsRequest.session_id:type_name -> SessionId
	2, // 1: FetchContainerLogsRequest.cluster_id:type_name -> ClusterId
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fetch_container_logs_request_proto_init() }
func file_fetch_container_logs_request_proto_init() {
	if File_fetch_container_logs_request_proto != nil {
		return
	}
	file_cluster_id_proto_init()
	file_session_id_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fetch_container_logs_request_proto_rawDesc), len(file_fetch_container_logs_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fetch_container_logs_request_proto_goTypes,
		DependencyIndexes: file_fetch_container_logs_request_proto_depIdxs,
		MessageInfos:      file_fetch_container_logs_request_proto_msgTypes,
	}.Build()
	File_fetch_container_logs_request_proto = out.File
	file_fetch_container_logs_request_proto_goTypes = nil
	file_fetch_container_logs_request_proto_depIdxs = nil
}
