// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sync_status.proto

package message_contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncStatusCode int32

const (
	SyncStatusCode_SYNC_STATUS_CODE_UNSPECIFIED   SyncStatusCode = 0
	SyncStatusCode_SYNC_STATUS_CODE_UNKNOWN       SyncStatusCode = 1
	SyncStatusCode_SYNC_STATUS_CODE_NOTAPPLICABLE SyncStatusCode = 2
	SyncStatusCode_SYNC_STATUS_CODE_INSYNC        SyncStatusCode = 3
	SyncStatusCode_SYNC_STATUS_CODE_OUTOFSYNC     SyncStatusCode = 4
)

// Enum value maps for SyncStatusCode.
var (
	SyncStatusCode_name = map[int32]string{
		0: "SYNC_STATUS_CODE_UNSPECIFIED",
		1: "SYNC_STATUS_CODE_UNKNOWN",
		2: "SYNC_STATUS_CODE_NOTAPPLICABLE",
		3: "SYNC_STATUS_CODE_INSYNC",
		4: "SYNC_STATUS_CODE_OUTOFSYNC",
	}
	SyncStatusCode_value = map[string]int32{
		"SYNC_STATUS_CODE_UNSPECIFIED":   0,
		"SYNC_STATUS_CODE_UNKNOWN":       1,
		"SYNC_STATUS_CODE_NOTAPPLICABLE": 2,
		"SYNC_STATUS_CODE_INSYNC":        3,
		"SYNC_STATUS_CODE_OUTOFSYNC":     4,
	}
)

func (x SyncStatusCode) Enum() *SyncStatusCode {
	p := new(SyncStatusCode)
	*p = x
	return p
}

func (x SyncStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_status_proto_enumTypes[0].Descriptor()
}

func (SyncStatusCode) Type() protoreflect.EnumType {
	return &file_sync_status_proto_enumTypes[0]
}

func (x SyncStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatusCode.Descriptor instead.
func (SyncStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_sync_status_proto_rawDescGZIP(), []int{0}
}

type SyncStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SyncStatusCode SyncStatusCode         `protobuf:"varint,1,opt,name=sync_status_code,json=syncStatusCode,proto3,enum=SyncStatusCode" json:"sync_status_code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JsonPatch      string                 `protobuf:"bytes,3,opt,name=json_patch,json=jsonPatch,proto3" json:"json_patch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncStatus) Reset() {
	*x = SyncStatus{}
	mi := &file_sync_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatus) ProtoMessage() {}

func (x *SyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sync_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatus.ProtoReflect.Descriptor instead.
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return file_sync_status_proto_rawDescGZIP(), []int{0}
}

func (x *SyncStatus) GetSyncStatusCode() SyncStatusCode {
	if x != nil {
		return x.SyncStatusCode
	}
	return SyncStatusCode_SYNC_STATUS_CODE_UNSPECIFIED
}

func (x *SyncStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncStatus) GetJsonPatch() string {
	if x != nil {
		return x.JsonPatch
	}
	return ""
}

var File_sync_status_proto protoreflect.FileDescriptor

const file_sync_status_proto_rawDesc = "" +
	"\n" +
	"\x11sync_status.proto\"\x80\x01\n" +
	"\n" +
	"SyncStatus\x129\n" +
	"\x10sync_status_code\x18\x01 \x01(\x0e2\x0f.SyncStatusCodeR\x0esyncStatusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"json_patch\x18\x03 \x01(\tR\tjsonPatch*\xb1\x01\n" +
	"\x0eSyncStatusCode\x12 \n" +
	"\x1cSYNC_STATUS_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SYNC_STATUS_CODE_UNKNOWN\x10\x01\x12\"\n" +
	"\x1eSYNC_STATUS_CODE_NOTAPPLICABLE\x10\x02\x12\x1b\n" +
	"\x17SYNC_STATUS_CODE_INSYNC\x10\x03\x12\x1e\n" +
	"\x1aSYNC_STATUS_CODE_OUTOFSYNC\x10\x04B\x91\x01B\x0fSyncStatusProtoP\x01ZNgithub.com/OctopusDeploy/kubernetes-monitor-contracts/go/pkg/message_contracts\xaa\x02+Octopus.Kubernetes.Monitor.MessageContractsb\x06proto3"

var (
	file_sync_status_proto_rawDescOnce sync.Once
	file_sync_status_proto_rawDescData []byte
)

func file_sync_status_proto_rawDescGZIP() []byte {
	file_sync_status_proto_rawDescOnce.Do(func() {
		file_sync_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_status_proto_rawDesc), len(file_sync_status_proto_rawDesc)))
	})
	return file_sync_status_proto_rawDescData
}

var file_sync_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sync_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sync_status_proto_goTypes = []any{
	(SyncStatusCode)(0), // 0: SyncStatusCode
	(*SyncStatus)(nil),  // 1: SyncStatus
}
var file_sync_status_proto_depIdxs = []int32{
	0, // 0: SyncStatus.sync_status_code:type_name -> SyncStatusCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sync_status_proto_init() }
func file_sync_status_proto_init() {
	if File_sync_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_status_proto_rawDesc), len(file_sync_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_status_proto_goTypes,
		DependencyIndexes: file_sync_status_proto_depIdxs,
		EnumInfos:         file_sync_status_proto_enumTypes,
		MessageInfos:      file_sync_status_proto_msgTypes,
	}.Build()
	File_sync_status_proto = out.File
	file_sync_status_proto_goTypes = nil
	file_sync_status_proto_depIdxs = nil
}
