name: "Check"
run-name: "Check"
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, labeled, unlabeled]

jobs: 
    check: 
        runs-on: ubuntu-latest
        permissions:
            statuses: write
            checks: write
            contents: read
            pull-requests: write 

        steps:
            - uses: actions/checkout@v4
            - name: Check for significant changes
              id: changed-files-specific
              uses: tj-actions/changed-files@v45
              with:
                files: |
                  **.proto
            - name: Buf 
              if: steps.changed-files-specific.outputs.any_changed == 'true'
              uses: bufbuild/buf-action@v1
              with: 
                push: false
                lint: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip lint') }}
                format: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip format') }}
                breaking: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'buf skip breaking') }}
                breaking_against: https://github.com/OctopusDeploy/kubernetes-monitor-contracts.git#branch=main,subdir=protos